package GUI;

import Domain.DescargadorFiltro;
import Domain.GuardarFiltro;
import Domain.Tuberia;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author unknown
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());
    
    private javax.swing.JTextArea areaMensajes;
    private javax.swing.JScrollPane scrollPaneMensajes;
    private String ultimoMp3 = null;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        areaMensajes = new javax.swing.JTextArea();
        scrollPaneMensajes = new javax.swing.JScrollPane();
        areaMensajes.setEditable(false);
        areaMensajes.setColumns(30);
        areaMensajes.setRows(10);
        scrollPaneMensajes.setViewportView(areaMensajes);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        convertirBtn = new javax.swing.JButton();
        escucharMp3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("jTextField1");

        convertirBtn.setText("jButton1");
        convertirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirBtnActionPerformed(evt);
            }
        });

        escucharMp3.setText("jButton1");
        escucharMp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escucharMp3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(convertirBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(escucharMp3)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertirBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(escucharMp3)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escucharMp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escucharMp3ActionPerformed
          if (ultimoMp3 != null)
        new ReproductorMp3(areaMensajes).reproducir(ultimoMp3);
    else
        areaMensajes.append("No hay ningún MP3 disponible para reproducir.\n");
    }//GEN-LAST:event_escucharMp3ActionPerformed

    private void convertirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirBtnActionPerformed
        String enlace = jTextField1.getText();

        Tuberia tuberia = new Tuberia(new DescargadorFiltro(areaMensajes),
        new ConvertidorFiltro(areaMensajes),
        new GuardarFiltro(areaMensajes)
    );

    ultimoMp3 = tuberia.ejecutar(enlace);

    if (ultimoMp3 != null)
        areaMensajes.append("Conversión completada: " + ultimoMp3 + "\n");
    else
        areaMensajes.append("Error en el proceso.\n");
    }//GEN-LAST:event_convertirBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertirBtn;
    private javax.swing.JButton escucharMp3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
